# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-21 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kw', models.CharField(max_length=10, unique=True, verbose_name='关键字')),
                ('count', models.IntegerField(default=1, verbose_name='出现次数')),
                ('disable', models.BooleanField(default=False, verbose_name='是否禁用')),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_created=True, auto_now=True, verbose_name='创建时间')),
                ('kw', models.CharField(max_length=10, verbose_name='关键字')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_created=True, auto_now=True, verbose_name='创建时间')),
                ('title', models.CharField(max_length=511, verbose_name='新闻标题')),
                ('news_url', models.CharField(max_length=1023, verbose_name='新闻链接')),
                ('publish_time', models.DateTimeField(verbose_name='新闻存在时间')),
                ('content', models.TextField(blank=True, default=None, help_text='保留字段', null=True, verbose_name='正文')),
            ],
        ),
    ]
