# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-23 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='news_id',
            field=models.CharField(default=None, max_length=20, verbose_name='唯一ID'),
        ),
        migrations.AddField(
            model_name='news',
            name='source',
            field=models.IntegerField(choices=[(-1, 'unknown'), (0, 'qdaily'), (1, 'cnbeta'), (2, 'techweb'), (3, 'sspai'), (4, 'leiphone')], default=-1, verbose_name='新闻源'),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_url',
            field=models.CharField(default=None, max_length=1023, verbose_name='新闻链接'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(default=None, max_length=511, verbose_name='新闻标题'),
        ),
    ]
