# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-23 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0002_auto_20170623_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_id',
            field=models.CharField(default=None, max_length=30, verbose_name='唯一ID'),
        ),
    ]
