# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-26 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0005_keyword_web_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='count',
            field=models.IntegerField(default=1, verbose_name='出现次数'),
        ),
        migrations.AddField(
            model_name='log',
            name='web_count',
            field=models.IntegerField(default=1, verbose_name='出现网站个数'),
        ),
    ]
