# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-26 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0006_auto_20170626_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='great',
            field=models.IntegerField(default=1, verbose_name='与期待值的倍数'),
        ),
    ]
