# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-03 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0007_log_great'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeywordGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=20, unique=True, verbose_name='组名')),
                ('count', models.IntegerField(default=1, verbose_name='出现次数')),
                ('web_count', models.IntegerField(default=1, verbose_name='出现网站个数')),
                ('disable', models.BooleanField(default=False, verbose_name='是否禁用')),
            ],
        ),
        migrations.AlterField(
            model_name='log',
            name='kw',
            field=models.CharField(max_length=20, verbose_name='关键字组名'),
        ),
        migrations.AlterField(
            model_name='news',
            name='source',
            field=models.IntegerField(choices=[(-1, 'unknown'), (0, 'qdaily'), (1, 'cnbeta'), (2, 'techweb'), (3, 'sspai'), (4, 'leiphone'), (5, 'dltle'), (6, 'ithome'), (7, '36kr')], default=-1, verbose_name='新闻源'),
        ),
    ]
