# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-03 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0009_keyword_group_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_id',
            field=models.CharField(default=None, max_length=50, unique=True, verbose_name='唯一ID'),
        ),
    ]
